In [1]:
import pandas as pd
import os
data_dir = 'data'
df_full = pd.read_csv(os.path.join(data_dir, 'train.csv'))
df_test = pd.read_csv(os.path.join(data_dir, 'test.csv'))

In [11]:
df_full

        id  time_of_event  time_of_alert  target
0     1924            NaN            NaN       0
1      822         19.500         18.633       1
2     1429            NaN            NaN       0
3      208         19.800         19.233       1
4     1904            NaN            NaN       0
...    ...            ...            ...     ...
1495   500         19.933         18.633       1
1496   519         19.567         19.033       1
1497   262         17.900         13.933       1
1498   391         19.867         19.267       1
1499   533         19.767         17.267       1

[1500 rows x 4 columns]

In [25]:
df_full

dataset_dir = 'data/images/train_500/'
image_dir = 'data/images/train_500/rgb'
os.remove(dataset_dir + 'annotations.txt')

for index, row in df_full.iterrows():
    folder = image_dir + '/' + f"{int(row['id']):05d}"
    
    video_name = f"{int(row['id']):05d}"
    start_frame = 60

    label = row['target']

    # Get end frame (last frame in folder)
    end_frame = len(os.listdir(folder))

    print(video_name, start_frame, end_frame, int(label))
    # delete annotations.txt
    # add to txt

    if row['id'] == 383:
        start_frame = 1
    with open(dataset_dir + 'annotations.txt', 'a') as f:
        f.write(f"{video_name} {start_frame} {end_frame} {int(label)}\n")

01924 60 180 0
00822 60 180 1
01429 60 180 0
00208 60 180 1
01904 60 180 0
00072 60 183 1
01486 60 181 0
01171 60 180 0
00128 60 179 1
01518 60 180 0
00205 60 183 1
01889 60 183 0
01286 60 180 0
00408 60 179 1
00948 60 179 1
00457 60 180 1
01267 60 180 0
01802 60 183 0
01755 60 183 0
00471 60 180 1
02134 60 162 0
00900 60 183 1
00841 60 180 1
00333 60 179 1
00564 60 173 1
00245 60 180 1
00171 60 179 1
01076 60 180 0
00795 60 184 1
00372 60 179 1
00938 60 180 1
01749 60 180 0
00884 60 183 1
00641 60 180 1
00010 60 180 1
01816 60 180 0
01052 60 180 0
01205 60 180 0
00927 60 180 1
00378 60 180 1
01579 60 183 0
01973 60 180 0
00238 60 179 1
01050 60 180 0
01204 60 180 0
00313 60 183 1
00876 60 184 1
00098 60 184 1
01505 60 180 0
01699 60 180 0
01972 60 180 0
00516 60 180 1
00357 60 184 1
00903 60 179 1
00880 60 180 1
02083 60 183 0
00558 60 183 1
01162 60 180 0
01438 60 183 0
01457 60 183 0
00291 60 183 1
01342 60 183 0
01236 60 183 0
00977 60 179 1
00100 60 179 1
01303 60 183 0
01250 60 183 0
01291 60 175 0
00765 60 183 1
02013 60 180 0
01022 60 180 1
00042 60 184 1
01906 60 153 0
00286 60 184 1
01653 60 180 0
00858 60 180 1
01405 60 180 0
00629 60 180 1
00145 60 180 1
01033 60 184 1
00292 60 180 1
01783 60 183 0
00611 60 180 1
01419 60 180 0
01016 60 184 1
01276 60 183 0
01352 60 180 0
00336 60 105 1
00168 60 180 1
00600 60 180 1
01425 60 180 0
01797 60 180 0
01829 60 180 0
01075 60 180 0
00473 60 179 1
01869 60 183 0
01551 60 183 0
00515 60 180 1
00058 60 183 1
00348 60 183 1
00487 60 179 1
01197 60 180 0
00335 60 179 1
00029 60 180 1
00960 60 184 1
01468 60 183 0
00980 60 179 1
00148 60 180 1
00301 60 179 1
00702 60 184 1
02067 60 183 0
01305 60 180 0
02026 60 183 0
00819 60 179 1
00459 60 180 1
00529 60 183 1
02001 60 180 0
01416 60 180 0
00425 60 180 1
01719 60 183 0
01103 60 180 0
00006 60 180 1
01717 60 183 0
01943 60 180 0
01624 60 183 0
01523 60 180 0
01322 60 179 0
00617 60 184 1
01714 60 180 0
02063 60 175 0
01728 60 179 0
02014 60 183 0
00705 60 183 1
00083 60 180 1
01261 60 180 0
01932 60 180 0
00032 60 180 1
02084 60 180 0
01041 60 180 0
02011 60 175 0
00861 60 180 1
00723 60 179 1
01791 60 179 0
00851 60 179 1
01193 60 180 0
01609 60 180 0
02049 60 141 0
01190 60 183 0
01698 60 180 0
02000 60 180 0
00370 60 179 1
01607 60 180 0
00355 60 180 1
00375 60 184 1
01801 60 180 0
01800 60 178 0
01341 60 183 0
01268 60 180 0
00437 60 179 1
01496 60 180 0
01394 60 180 0
00477 60 180 1
00077 60 179 1
00068 60 180 1
00986 60 180 1
00587 60 180 1
01138 60 180 0
01037 60 179 1
00109 60 180 1
01942 60 178 0
00498 60 159 1
00312 60 183 1
01292 60 180 0
02139 60 180 0
01600 60 179 0
01313 60 180 0
00673 60 179 1
01988 60 183 0
01679 60 180 0
01135 60 180 0
00440 60 180 1
01321 60 180 0
02052 60 180 0
00614 60 180 1
01817 60 183 0
01219 60 180 0
00963 60 179 1
02121 60 180 0
00450 60 184 1
00435 60 180 1
00201 60 180 1
01798 60 180 0
00441 60 180 1
00300 60 180 1
00847 60 184 1
00901 60 180 1
01601 60 180 0
00651 60 180 1
01657 60 183 0
01289 60 175 0
00056 60 180 1
01953 60 179 0
00604 60 181 1
01647 60 183 0
01084 60 180 0
00164 60 180 1
00423 60 180 1
00410 60 180 1
00998 60 175 1
01928 60 175 0
00190 60 179 1
00223 60 180 1
01444 60 178 0
00284 60 183 1
00373 60 186 1
01570 60 180 0
01578 60 180 0
01631 60 180 0
00260 60 179 1
00037 60 180 1
00340 60 185 1
01765 60 175 0
01812 60 183 0
01893 60 180 0
00890 60 179 1
00371 60 183 1
01726 60 179 0
00434 60 180 1
01526 60 179 0
00206 60 180 1
00665 60 182 1
01187 60 177 0
00401 60 179 1
00885 60 184 1
01596 60 180 0
01278 60 180 0
02089 60 180 0
01708 60 183 0
01465 60 180 0
00985 60 179 1
01544 60 183 0
00635 60 179 1
00099 60 182 1
01761 60 180 0
00123 60 179 1
01070 60 173 0
00771 60 184 1
00455 60 184 1
01414 60 180 0
00677 60 180 1
00810 60 184 1
00181 60 178 1
00547 60 179 1
02039 60 178 0
02046 60 179 0
00695 60 179 1
00079 60 180 1
00334 60 179 1
01671 60 180 0
00751 60 180 1
00430 60 179 1
01255 60 176 0
00461 60 180 1
00940 60 184 1
00381 60 179 1
01963 60 180 0
00460 60 182 1
00090 60 179 1
00645 60 180 1
00132 60 179 1
01484 60 175 0
01036 60 180 1
00605 60 184 1
01724 60 180 0
01824 60 183 0
01849 60 180 0
01538 60 183 0
00040 60 180 1
01420 60 180 0
00719 60 180 1
00813 60 180 1
01256 60 180 0
00295 60 180 1
00773 60 180 1
00656 60 180 1
01649 60 180 0
00589 60 180 1
01839 60 174 0
00588 60 180 1
00540 60 184 1
01122 60 180 0
01737 60 183 0
01390 60 183 0
01249 60 180 0
01368 60 180 0
01871 60 180 0
01687 60 180 0
01294 60 183 0
01987 60 180 0
00557 60 180 1
00704 60 178 1
01996 60 180 0
00563 60 179 1
01588 60 180 0
01000 60 184 1
00949 60 184 1
01752 60 183 0
00179 60 180 1
00591 60 177 1
02016 60 180 0
00755 60 180 1
00932 60 180 1
00021 60 180 1
01437 60 180 0
00727 60 180 1
00263 60 179 1
00921 60 179 1
00833 60 180 1
00066 60 179 1
01723 60 180 0
01281 60 179 0
00431 60 179 1
00152 60 184 1
01696 60 183 0
00577 60 183 1
01950 60 180 0
01426 60 180 0
00845 60 180 1
01912 60 180 0
00776 60 167 1
01767 60 179 0
01793 60 179 0
00520 60 183 1
01224 60 180 0
02040 60 180 0
00761 60 180 1
00590 60 184 1
01713 60 180 0
02118 60 183 0
01640 60 180 0
00802 60 184 1
00666 60 180 1
00791 60 180 1
01112 60 183 0
00699 60 180 1
00868 60 179 1
00005 60 184 1
00004 60 179 1
00877 60 179 1
00319 60 179 1
02105 60 183 0
01159 60 180 0
01994 60 180 0
01324 60 180 0
01887 60 180 0
00668 60 179 1
01167 60 180 0
00209 60 180 1
00111 60 179 1
00202 60 180 1
02133 60 180 0
00506 60 184 1
00354 60 179 1
01383 60 180 0
00730 60 173 1
00731 60 180 1
02071 60 183 0
01870 60 180 0
02055 60 183 0
02130 60 180 0
00961 60 180 1
01090 60 180 0
01299 60 180 0
01404 60 183 0
01574 60 180 0
00601 60 180 1
00255 60 180 1
01395 60 183 0
00031 60 180 1
00683 60 183 1
00936 60 179 1
00598 60 180 1
00343 60 183 1
00318 60 175 1
00671 60 180 1
01681 60 180 0
01108 60 180 0
01811 60 180 0
00175 60 179 1
01693 60 180 0
01627 60 183 0
00955 60 180 1
00834 60 183 1
01098 60 180 0
00603 60 183 1
00240 60 184 1
01448 60 180 0
01865 60 179 0
00388 60 183 1
00843 60 177 1
00887 60 179 1
01019 60 179 1
01374 60 180 0
01539 60 180 0
00722 60 180 1
00904 60 184 1
01541 60 180 0
00785 60 180 1
00014 60 179 1
00593 60 180 1
00869 60 180 1
00015 60 180 1
02115 60 183 0
01969 60 180 0
00621 60 180 1
00049 60 180 1
01003 60 184 1
01810 60 179 0
01242 60 180 0
01983 60 180 0
01100 60 179 0
00167 60 180 1
00669 60 183 1
00117 60 180 1
00690 60 180 1
01900 60 177 0
00494 60 184 1
00857 60 184 1
01603 60 180 0
00599 60 179 1
01740 60 183 0
00235 60 179 1
01517 60 180 0
00369 60 179 1
00057 60 180 1
02033 60 143 0
00071 60 180 1
01339 60 174 0
00026 60 180 1
01298 60 183 0
01259 60 180 0
01629 60 179 0
02069 60 180 0
00729 60 184 1
01441 60 180 0
02114 60 180 0
01908 60 183 0
02095 60 183 0
01896 60 180 0
02075 60 180 0
00897 60 180 1
00856 60 180 1
01823 60 183 0
01413 60 180 0
00607 60 176 1
00947 60 180 1
00902 60 179 1
01669 60 180 0
00622 60 180 1
00854 60 180 1
01364 60 180 0
00643 60 180 1
01558 60 180 0
00013 60 179 1
00562 60 180 1
01235 60 180 0
01874 60 180 0
00976 60 179 1
01754 60 180 0
01461 60 180 0
00298 60 184 1
01710 60 180 0
01577 60 179 0
01081 60 180 0
01326 60 183 0
01136 60 175 0
01954 60 170 0
01218 60 180 0
01013 60 180 1
00881 60 183 1
00131 60 186 1
00469 60 171 1
01115 60 183 0
00214 60 184 1
01114 60 183 0
00831 60 182 1
01842 60 174 0
02041 60 183 0
00173 60 180 1
01605 60 180 0
01495 60 179 0
00124 60 180 1
01557 60 180 0
00543 60 179 1
00108 60 180 1
00777 60 179 1
01234 60 174 0
01035 60 183 1
01097 60 179 0
00882 60 179 1
01092 60 180 0
01583 60 180 0
00745 60 180 1
01049 60 183 0
01074 60 180 0
01611 60 180 0
01638 60 180 0
01393 60 180 0
01564 60 180 0
00664 60 180 1
00216 60 179 1
01372 60 180 0
01493 60 179 0
00158 60 179 1
00889 60 180 1
01069 60 180 0
02079 60 180 0
01722 60 180 0
00151 60 179 1
00586 60 174 1
01848 60 180 0
01756 60 180 0
00189 60 180 1
01279 60 180 0
00155 60 183 1
00694 60 180 1
00638 60 184 1
00891 60 180 1
01521 60 180 0
00226 60 180 1
00965 60 184 1
00667 60 180 1
00991 60 180 1
01890 60 180 0
02004 60 180 0
01323 60 183 0
01377 60 173 0
00538 60 179 1
00330 60 180 1
00763 60 180 1
01400 60 178 0
00105 60 180 1
02006 60 183 0
01011 60 182 1
00320 60 180 1
02042 60 174 0
00141 60 183 1
00783 60 184 1
01858 60 180 0
00630 60 184 1
00709 60 180 1
01781 60 180 0
02031 60 180 0
01546 60 183 0
01528 60 180 0
01343 60 163 0
00931 60 180 1
00682 60 180 1
00184 60 180 1
01386 60 178 0
00580 60 180 1
02070 60 183 0
00044 60 180 1
01979 60 180 0
00910 60 179 1
01132 60 177 0
01176 60 180 0
01750 60 180 0
02028 60 179 0
02003 60 180 0
00978 60 184 1
01655 60 183 0
01815 60 183 0
00225 60 179 1
01121 60 180 0
01147 60 158 0
00913 60 179 1
00928 60 180 1
01263 60 180 0
00639 60 179 1
01415 60 179 0
01939 60 180 0
00873 60 182 1
00310 60 181 1
00061 60 180 1
02007 60 179 0
00995 60 180 1
00937 60 179 1
01536 60 180 0
01975 60 180 0
01222 60 144 0
00528 60 180 1
01211 60 180 0
00943 60 182 1
01599 60 180 0
01230 60 180 0
01566 60 180 0
01361 60 180 0
00618 60 179 1
02111 60 183 0
00493 60 180 1
00602 60 180 1
00149 60 180 1
00324 60 179 1
00688 60 183 1
00237 60 179 1
00064 60 179 1
00488 60 180 1
00380 60 180 1
00387 60 181 1
02002 60 180 0
00657 60 180 1
00144 60 180 1
01529 60 180 0
00670 60 179 1
00467 60 180 1
01853 60 180 0
00289 60 180 1
01172 60 180 0
02097 60 180 0
01072 60 180 0
00697 60 180 1
00967 60 180 1
00110 60 180 1
00019 60 184 1
01272 60 180 0
00022 60 180 1
00898 60 180 1
00417 60 180 1
00270 60 180 1
00251 60 176 1
00918 60 175 1
01819 60 180 0
01073 60 178 0
01806 60 183 0
00970 60 183 1
01024 60 179 1
01881 60 180 0
01977 60 180 0
00143 60 182 1
01191 60 180 0
00742 60 178 1
01654 60 180 0
01725 60 180 0
00016 60 178 1
00036 60 181 1
01678 60 183 0
01660 60 180 0
01913 60 180 0
01733 60 180 0
01530 60 179 0
01439 60 180 0
00503 60 180 1
01265 60 180 0
00084 60 184 1
01533 60 180 0
00046 60 180 1
00762 60 180 1
01705 60 180 0
00102 60 179 1
01042 60 180 0
01778 60 179 0
01423 60 180 0
02108 60 183 0
00254 60 180 1
00122 60 179 1
01045 60 177 0
00376 60 184 1
01031 60 180 1
00411 60 180 1
00405 60 180 1
00166 60 182 1
00642 60 181 1
00707 60 181 1
00308 60 183 1
00135 60 180 1
01604 60 183 0
01206 60 183 0
00691 60 180 1
01616 60 175 0
01487 60 176 0
01768 60 180 0
00085 60 179 1
01388 60 179 0
00059 60 180 1
00217 60 180 1
01287 60 180 0
01477 60 183 0
00644 60 184 1
01951 60 180 0
00418 60 180 1
00584 60 180 1
02072 60 172 0
00082 60 179 1
01617 60 180 0
00823 60 180 1
01944 60 183 0
00983 60 180 1
01971 60 183 0
00754 60 180 1
01165 60 180 0
00820 60 180 1
00703 60 180 1
01328 60 180 0
01397 60 183 0
00133 60 182 1
00282 60 179 1
01840 60 180 0
00194 60 183 1
01311 60 183 0
01039 60 179 1
00395 60 182 1
00180 60 180 1
01506 60 180 0
00909 60 180 1
00769 60 180 1
00594 60 183 1
00784 60 180 1
01195 60 180 0
01683 60 180 0
00827 60 180 1
00828 60 179 1
02019 60 180 0
01634 60 183 0
01144 60 178 0
00570 60 179 1
00715 60 174 1
00195 60 180 1
01807 60 183 0
01102 60 180 0
00565 60 179 1
01290 60 183 0
01058 60 183 0
00429 60 180 1
01525 60 180 0
01805 60 180 0
00496 60 183 1
01563 60 180 0
01071 60 180 0
01606 60 180 0
01901 60 180 0
01926 60 183 0
00968 60 179 1
00331 60 183 1
00661 60 180 1
00063 60 179 1
00546 60 179 1
00078 60 180 1
00735 60 180 1
00269 60 183 1
01656 60 180 0
00294 60 180 1
00997 60 183 1
01970 60 180 0
00838 60 180 1
00658 60 179 1
00138 60 180 1
00608 60 174 1
00023 60 180 1
01488 60 180 0
01697 60 183 0
00224 60 179 1
01741 60 180 0
00160 60 180 1
01910 60 178 0
01916 60 180 0
01238 60 183 0
00626 60 179 1
00244 60 185 1
00623 60 184 1
00444 60 179 1
01350 60 180 0
00393 60 180 1
01843 60 183 0
01131 60 180 0
01494 60 183 0
00872 60 179 1
00443 60 185 1
00000 60 173 1
00349 60 184 1
00466 60 180 1
00283 60 180 1
01771 60 180 0
00449 60 177 1
00517 60 183 1
00740 60 180 1
00640 60 183 1
00911 60 174 1
01501 60 180 0
01507 60 180 0
02092 60 180 0
01673 60 180 0
00522 60 184 1
01822 60 180 0
00958 60 179 1
01966 60 180 0
00747 60 179 1
01079 60 180 0
00252 60 179 1
00366 60 179 1
00177 60 179 1
00361 60 182 1
01491 60 179 0
00060 60 184 1
00407 60 180 1
00966 60 175 1
01584 60 180 0
01384 60 180 0
01921 60 177 0
00567 60 182 1
00737 60 180 1
01269 60 183 0
00228 60 183 1
01463 60 180 0
01772 60 183 0
02102 60 180 0
01489 60 180 0
01109 60 180 0
00573 60 180 1
01293 60 179 0
01661 60 179 0
00895 60 183 1
00774 60 180 1
01229 60 180 0
00678 60 179 1
00824 60 179 1
00345 60 179 1
01695 60 179 0
01508 60 183 0
00818 60 180 1
01639 60 180 0
00866 60 179 1
00788 60 184 1
01894 60 183 0
01060 60 179 0
01680 60 180 0
00556 60 179 1
01476 60 180 0
01590 60 173 0
01470 60 180 0
01130 60 183 0
00875 60 182 1
00317 60 180 1
01232 60 180 0
00915 60 180 1
01964 60 183 0
00106 60 180 1
00675 60 180 1
02018 60 180 0
02060 60 183 0
00714 60 180 1
00392 60 169 1
01922 60 180 0
01537 60 180 0
01742 60 183 0
00846 60 184 1
00527 60 180 1
01747 60 180 0
00130 60 180 1
01085 60 183 0
02126 60 183 0
01066 60 180 0
00512 60 182 1
00957 60 177 1
02027 60 180 0
00836 60 179 1
00329 60 180 1
01227 60 180 0
01960 60 180 0
01067 60 183 0
00906 60 180 1
01360 60 183 0
01568 60 180 0
00805 60 184 1
00453 60 184 1
00926 60 180 1
00692 60 184 1
01348 60 180 0
01736 60 183 0
01213 60 180 0
00125 60 183 1
02132 60 180 0
00097 60 179 1
01078 60 180 0
00247 60 184 1
00398 60 180 1
01980 60 180 0
01258 60 183 0
01399 60 180 0
00655 60 177 1
00018 60 179 1
01844 60 183 0
01225 60 180 0
01704 60 180 0
00344 60 182 1
01952 60 183 0
00990 60 183 1
01482 60 180 0
00917 60 179 1
01991 60 179 0
00568 60 180 1
01780 60 183 0
01355 60 180 0
00311 60 184 1
00739 60 184 1
01845 60 180 0
01707 60 180 0
00039 60 179 1
01949 60 183 0
02119 60 180 0
00865 60 179 1
00427 60 181 1
01446 60 179 0
01379 60 180 0
01210 60 180 0
01002 60 174 1
01662 60 183 0
00636 60 183 1
00416 60 184 1
01917 60 180 0
01492 60 179 0
01739 60 147 0
01632 60 180 0
00539 60 183 1
00809 60 179 1
02080 60 180 0
01214 60 180 0
01572 60 180 0
01421 60 180 0
00830 60 184 1
01317 60 176 0
00832 60 180 1
00863 60 170 1
01763 60 179 0
00483 60 179 1
01433 60 172 0
01266 60 180 0
00491 60 180 1
00024 60 180 1
01985 60 180 0
00363 60 184 1
02053 60 180 0
00581 60 183 1
02066 60 179 0
01773 60 180 0
01716 60 180 0
01860 60 180 0
00606 60 180 1
01785 60 177 0
01888 60 180 0
00789 60 183 1
02059 60 180 0
00627 60 180 1
01344 60 183 0
00741 60 184 1
01500 60 183 0
00495 60 180 1
02085 60 180 0
02035 60 178 0
01623 60 180 0
00287 60 184 1
01088 60 180 0
00458 60 179 1
00526 60 178 1
00713 60 180 1
00859 60 184 1
00089 60 180 1
01240 60 180 0
00342 60 179 1
00596 60 179 1
00339 60 160 1
01028 60 180 1
01408 60 180 0
01770 60 183 0
00972 60 176 1
01504 60 179 0
01061 60 180 0
01270 60 174 0
01277 60 180 0
01141 60 180 0
00700 60 179 1
01748 60 173 0
01254 60 180 0
01986 60 180 0
01548 60 183 0
00624 60 180 1
02054 60 180 0
01527 60 178 0
01357 60 180 0
01690 60 173 0
00923 60 183 1
02012 60 183 0
01760 60 180 0
01766 60 179 0
01207 60 180 0
01435 60 180 0
01012 60 179 1
00153 60 179 1
01260 60 180 0
00341 60 179 1
00579 60 180 1
00234 60 180 1
00583 60 184 1
00456 60 180 1
00095 60 180 1
00424 60 179 1
01140 60 180 0
00041 60 179 1
00988 60 180 1
01134 60 176 0
00981 60 178 1
01990 60 180 0
01586 60 180 0
01666 60 173 0
01453 60 183 0
00142 60 179 1
02088 60 178 0
01332 60 180 0
01941 60 180 0
00835 60 180 1
00650 60 179 1
01282 60 183 0
00276 60 179 1
00849 60 180 1
01694 60 180 0
00232 60 180 1
00147 60 180 1
00744 60 184 1
00351 60 179 1
00609 60 184 1
02124 60 180 0
00403 60 179 1
01875 60 180 0
00793 60 179 1
01706 60 179 0
01170 60 180 0
00693 60 183 1
01880 60 180 0
00103 60 179 1
01729 60 180 0
00129 60 179 1
00275 60 180 1
00633 60 179 1
00172 60 180 1
01795 60 180 0
02064 60 174 0
01096 60 183 0
00571 60 183 1
00027 60 179 1
01380 60 180 0
01434 60 180 0
01664 60 173 0
00307 60 179 1
01948 60 178 0
01288 60 180 0
01976 60 180 0
00264 60 182 1
01792 60 180 0
00136 60 183 1
00816 60 179 1
00959 60 180 1
01608 60 180 0
01503 60 180 0
02074 60 183 0
01396 60 180 0
00047 60 179 1
00551 60 180 1
00549 60 180 1
01645 60 183 0
00296 60 180 1
00096 60 152 1
00734 60 183 1
00480 60 184 1
02096 60 181 0
02045 60 183 0
00864 60 180 1
00674 60 184 1
00017 60 180 1
01542 60 180 0
00935 60 175 1
01319 60 183 0
01735 60 180 0
02136 60 183 0
00475 60 183 1
01054 60 175 0
00188 60 177 1
01828 60 180 0
01417 60 183 0
00302 60 179 1
00634 60 180 1
02017 60 177 0
00701 60 180 1
00637 60 179 1
02104 60 180 0
00758 60 180 1
01510 60 183 0
01753 60 183 0
00163 60 186 1
01630 60 183 0
00502 60 179 1
01116 60 180 0
00652 60 179 1
00825 60 180 1
02087 60 180 0
01532 60 183 0
00119 60 183 1
01043 60 180 0
01643 60 180 0
01178 60 180 0
01612 60 180 0
00303 60 179 1
01182 60 183 0
01306 60 183 0
00929 60 179 1
01004 60 176 1
01878 60 180 0
00288 60 183 1
00065 60 180 1
00782 60 180 1
02051 60 178 0
00748 60 180 1
01485 60 183 0
01866 60 183 0
02062 60 180 0
00364 60 183 1
01582 60 180 0
00048 60 180 1
01315 60 180 0
00210 60 180 1
00321 60 179 1
00426 60 184 1
01702 60 180 0
01550 60 180 0
01128 60 183 0
00553 60 184 1
00916 60 184 1
00478 60 183 1
00944 60 180 1
01903 60 175 0
00327 60 184 1
00187 60 184 1
01333 60 180 0
00534 60 183 1
00686 60 179 1
00256 60 179 1
01621 60 180 0
00452 60 180 1
00867 60 180 1
01285 60 183 0
02135 60 180 0
02024 60 183 0
01935 60 180 0
00554 60 184 1
02044 60 180 0
00093 60 180 1
01934 60 183 0
01625 60 180 0
00860 60 180 1
01882 60 183 0
00798 60 183 1
02034 60 180 0
01146 60 180 0
00971 60 180 1
01473 60 177 0
01545 60 180 0
01295 60 183 0
01020 60 183 1
00222 60 180 1
00766 60 179 1
00259 60 184 1
01456 60 180 0
00660 60 178 1
00687 60 184 1
01967 60 180 0
00414 60 180 1
00725 60 180 1
00360 60 180 1
00803 60 180 1
00942 60 179 1
00233 60 180 1
02099 60 180 0
00285 60 184 1
01598 60 178 0
01354 60 180 0
01933 60 178 0
01118 60 180 0
00839 60 179 1
00698 60 179 1
01262 60 180 0
01194 60 176 0
01835 60 180 0
00905 60 180 1
00464 60 180 1
00787 60 180 1
00497 60 179 1
00485 60 180 1
01411 60 179 0
00358 60 180 1
00792 60 180 1
00653 60 175 1
01968 60 180 0
01929 60 175 0
00566 60 179 1
00996 60 180 1
00912 60 184 1
01879 60 183 0
00290 60 184 1
00169 60 185 1
00817 60 183 1
01362 60 162 0
01142 60 180 0
00028 60 184 1
01382 60 180 0
01920 60 176 0
00647 60 180 1
00521 60 174 1
01585 60 176 0
00979 60 184 1
00850 60 180 1
00712 60 180 1
01034 60 179 1
00982 60 183 1
00952 60 183 1
00054 60 180 1
01955 60 183 0
00003 60 180 1
01271 60 180 0
00953 60 184 1
01663 60 180 0
00008 60 179 1
01554 60 180 0
01834 60 180 0
00964 60 179 1
01497 60 179 0
01936 60 180 0
00663 60 182 1
00542 60 184 1
01691 60 180 0
00804 60 180 1
01581 60 180 0
01095 60 180 0
01511 60 180 0
02037 60 180 0
01995 60 180 0
01534 60 183 0
00696 60 184 1
01559 60 183 0
00794 60 184 1
00328 60 186 1
01846 60 183 0
01089 60 172 0
01825 60 180 0
01732 60 180 0
02120 60 179 0
01048 60 183 0
01899 60 183 0
01252 60 180 0
01173 60 180 0
01401 60 183 0
01454 60 180 0
01283 60 180 0
00433 60 180 1
00625 60 181 1
01157 60 180 0
01499 60 180 0
01711 60 179 0
01925 60 180 0
00757 60 179 1
00560 60 175 1
01196 60 180 0
00574 60 184 1
01365 60 183 0
00081 60 179 1
01646 60 183 0
01571 60 183 0
01734 60 180 0
00914 60 184 1
00750 60 176 1
01821 60 180 0
01046 60 183 0
01248 60 183 0
01062 60 180 0
00753 60 180 1
00613 60 180 1
00383 60 76 1
00481 60 180 1
01366 60 180 0
01175 60 179 0
00415 60 180 1
00840 60 180 1
01552 60 180 0
00585 60 180 1
00114 60 180 1
00930 60 180 1
00162 60 179 1
01177 60 183 0
02129 60 180 0
01961 60 180 0
01885 60 180 0
01301 60 180 0
01789 60 180 0
01786 60 183 0
01228 60 182 0
01431 60 180 0
01709 60 180 0
00592 60 180 1
01685 60 180 0
00780 60 179 1
01580 60 183 0
00200 60 184 1
01931 60 179 0
00356 60 180 1
01959 60 180 0
00362 60 180 1
01318 60 180 0
01827 60 174 0
00874 60 183 1
00174 60 180 1
00239 60 180 1
01852 60 180 0
00659 60 184 1
01519 60 183 0
01094 60 179 0
01712 60 171 0
01338 60 180 0
01614 60 180 0
02061 60 180 0
01464 60 180 0
00945 60 177 1
01237 60 180 0
00213 60 179 1
00888 60 180 1
02032 60 183 0

In [19]:
df_full[df_full['id'] == 1755]

      id  time_of_event  time_of_alert  target
18  1755            NaN            NaN       0